
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const CHANGE_PRIMARY_COLOR = "CHANGE_PRIMARY_COLOR"
export const CHANGE_SECONDARY_COLOR = "CHANGE_SECONDARY_COLOR"

export const LOCAL_STORAGE_PRIMARY_COLOR = "LOCAL_STORAGE_PRIMARY_COLOR"
export const LOCAL_STORAGE_SECONDARY_COLOR = "LOCAL_STORAGE_SECONDARY_COLOR"