
export const IS_LOGGED_IN = "IS_LOGGED_IN";
export const CHANGE_PRIMARY_COLOR = "CHANGE_PRIMARY_COLOR"
export const CHANGE_SECONDARY_COLOR = "CHANGE_SECONDARY_COLOR"

export const LOCAL_STORAGE_PRIMARY_COLOR = "LOCAL_STORAGE_PRIMARY_COLOR"
export const LOCAL_STORAGE_SECONDARY_COLOR = "LOCAL_STORAGE_SECONDARY_COLOR"

export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER = "GET_USER";

export const ROOT_URL = "http://159.69.117.200:8080"